version: '3.7'

services:
  tester:
    build:
      context: .
    tty: true
    volumes:
      - ./conf/BasicSimulation.scala:/opt/gatling/conf/BasicSimulation.scala
      - ./user-files:/opt/gatling/user-files
      - ./results:/opt/gatling/results
    network_mode: host
    command: ['-rd', 'My test']