# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "sylabs/singularity-3.5-ubuntu-bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
